### ISSUE TITLE
Node PDX Cycle Explorations of Portland

### ISSUE THREAD

**Issue by Adron** [nodepdx/nodepdx.github.com#84]
Previous rides I've lead for conferences stopped by Ristretto Roasters (for a local roasted coffee), Velo Cult (Bicycle Culture) for a local micro-brew, and rolled back through town checking out various places. I'm game for any number of options or ideas. Send em' this way!

**Comment by cruisercohen** [comment]
I'm down for some nerd biking, coffee and micro-brew sound about right. Ground Kontrol is always fun. Apex for good outdoor beer. Mt. Tabor or other parks for views and semi-nature. Really are lots of great options.

**Comment by Adron** [comment]
Will be posting the bike route soon @cruisercohen so stay tuned!  👍

**Comment by simplesthing** [comment]
Do you have any idea when the ride will start, planning on driving up from Seattle to make the ride and want to make sure I can make it.

**Comment by Adron** [comment]
Hey @simplesthing I'm just about to post info on the ride(s) on the Node PDX site.  👍 

The plan right now is to have the ride the day of the Geek Train, about an hour after our arrival on the train that Saturday. http://nodepdx.org/geek-train.html

However - I'm also pondering another ride the evening of Sunday, the day before the conference (which we're also aiming to have some other events that day, which we'll just ride up to after the bike ride on Sunday. That one will likely be about ~5:30ish. If you'd like to see anything or have any suggestions we're still pretty flexible on timing.
